apiVersion: v1
entries:
  sunbird-rc:
  - apiVersion: v2
    appVersion: 0.0.13
    created: "2023-11-16T08:10:13.891417474Z"
    description: A Helm chart for Sunbird RC
    digest: 8d03600fd115777d1de78030808090973b871fb5bde6e4463a8229b2239d4072
    name: sunbird-rc
    type: application
    urls:
    - https://amitvashist7.github.io/helm-example/sunbird-rc-0.5.0.tgz
    version: 0.5.0
generated: "2023-11-16T08:10:13.864396559Z"
